#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@filebrowser[-1]
	add ucitrack filebrowser
	set ucitrack.@filebrowser[-1].init=filebrowser
	commit ucitrack
EOF

chmod +x /etc/init.d/filebrowser
rm -f /tmp/luci-indexcache
exit 0
